import Head from 'next/head'

import Landing from "../components/landing";
import React, {useState} from "react";
import Popup from "../components/popup";

export default function Home() {

    const [statusPopup , setStatusPopup] = useState(false)


    return (<div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
        </Head>
        <main className='container-fluid font-pinar p-0 m-0 vh-100 main'>
            <Landing setStatusPopup={setStatusPopup}/>
        </main>
        {
            statusPopup ?   <Popup setStatusPopup={setStatusPopup} />  : ''
        }

    </div>)
}
